language: node_js

before_install:
  - export JOBS=max
  - npm install -g node-gyp-install
  - node-gyp-install

node_js:
  - "2.2"
  - "2.1"
  - "2.0"
  - "1.8"
  - "0.12"
  - "0.10"

script:
  - npm test

