language: node_js

jobs:
  include:
    - os: linux
      node_js: 8
      env: [TEST=1]
    - os: linux
      node_js: 10
      env: [TEST=1]
    - os: linux
      node_js: node
      env: [TEST=1, TEST_ELECTRON=1, BUILD_CMD=prebuild, BUILD_GROUP=linux-x64]
      addons:
        apt:
          packages:
            - xvfb
      install:
        - export DISPLAY=':99.0'
        - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - os: osx
      node_js: 8
      env: [TEST=1]
    - os: osx
      node_js: 10
      env: [TEST=1]
    - os: osx
      node_js: node
      env: [TEST=1, TEST_ELECTRON=1, BUILD_CMD=prebuild, BUILD_GROUP=darwin-x64]
    - name: arm
      os: linux
      node_js: node
      env: [BUILD_CMD=prebuild-arm, BUILD_GROUP=arm]
      if: tag is present

script:
  - if [[ ! -z "$TEST" ]]; then npm run test; fi
  - if [[ ! -z "$TEST_ELECTRON" ]]; then npm run test-electron; fi

after_success:
  - if [[ ! -z "$TEST" ]]; then npm run coverage; fi

before_deploy:
  - export ARCHIVE_NAME="${TRAVIS_TAG:-latest}-$BUILD_GROUP.tar.gz"
  - npm run $BUILD_CMD
  - file prebuilds/*/*
  - tar -zcvf "$ARCHIVE_NAME" -C prebuilds .

deploy:
  provider: releases
  draft: false
  api_key: "$PREBUILD_TOKEN"
  file: "$ARCHIVE_NAME"
  skip_cleanup: true
  on:
    tags: true
    condition: "! -z $BUILD_CMD"
